#!/bin/env python
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

from hooks_support import git_func
from hooks_support.file_manager import create_json, read_json

diff_data = git_func.get_diff(local_git_path='../../.git')
diff_data_path = create_json(name='diff_data', path='../../', data=diff_data)
print(read_json('../../diff_data.json'))